#!/bin/bash

echo "🚀 Deploying Castle OAuth Consent to GitHub..."
echo ""
echo "📋 After creating your GitHub repository, run these commands:"
echo ""
echo "# Add remote (replace YOUR_USERNAME with your GitHub username)"
echo "git remote add origin https://github.com/YOUR_USERNAME/castle-oauth-consent.git"
echo ""
echo "# Push to GitHub"
echo "git push -u origin main"
echo ""
echo "✅ Your repository will be available at:"
echo "https://github.com/YOUR_USERNAME/castle-oauth-consent"
echo ""
echo "🎉 Features included in this repository:"
echo "✅ Complete OAuth 2.0 + PKCE implementation"
echo "✅ Modern Next.js 14 with TypeScript"
echo "✅ Responsive Tailwind CSS design"
echo "✅ Comprehensive test suite (Playwright)"
echo "✅ Docker deployment support"
echo "✅ CI/CD workflow (GitHub Actions)"
echo "✅ Production-ready build system"
echo "✅ Complete documentation"

